- name: shipping
  hosts: shipping
  become: yes
  vars:
    mysql_password: Roboshop@1
  tasks:
    - name: install maven 
      ansible.builtin.dnf: 
        name: maven
        state: present

    - name: create roboshop user
      ansible.builtin.user:
        name: roboshop
        
    - name: recursively delete existing dir
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create new dir
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download shipping Application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /tmp

    - name: extract the shipping App
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes 

    - name: install dependencies
      ansible.builtin.command: mvn clean package
      args:
       chdir: /app

    - name: rename Jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: copying shipping.service
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: daemon-reload
      ansible.builtin.systemd_service:
        daemon-reload: true

    - name: install mysql client
      ansible.builtin.dnf:
        name: mysql
        state: present

    - name: check cities schema exists or not
      ansible.builtin.shell:  mysql -h mysql.devopsju.online -uroot -p{{mysql_password}} -sN -e  "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'";
      register: schema

    - name: print output
      ansible.builtin.debug:
        msg: "schema output: {{schema}}"

    - name: load cities data
      ansible.builtin.shell: "mysql -h mysql.devopsju.online -uroot -p{{mysql_password}}  < /app/schema/shipping.sql"
      when: schema.stdout != "1"

    - name: start & enable shipping
      ansible.builtin.service:
        name: shipping
        state: restarted
        enabled: yes
    

     
