- name: install User component
  hosts: user
  become: yes
  tasks:
    - name: disable & enable nodejs version
      ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: create roboship user
      ansible.builtin.user:
        name: roboshop

    - name: delete existing dir
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create new dir
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download the Application
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/user.zip
        dest: /tmp

    - name: Extract the Application
      ansible.builtin.unarchive:
        src: /tmp/user.zip
        dest: /app
        remote_src : yes

    - name: download & install dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: copy user service
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: daemon reload & start
      ansible.builtin.systemd_service:
        daemon_reload: true

    # lets start after the data is loaded
    
    - name: copy mongodb repo
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: install mongodb client
      ansible.builtin.package:
        name: mongodb-org-shell
        state: present

    - name: get the users count
      ansible.builtin.command: mongo --host mongodb.devopsju.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
      register: user_count

    - name: print the count
      ansible.builtin.debug:
        msg: "user-count : {{user_count}}"

    - name: load user data
      ansible.builtin.command: mongo --host mongodb.devopsju.online < /app/schema/user.js
      when: user_count.stdout == "0" # keep double quotes

    - name: start & enable user
      ansible.builtin.service:
        name: user
        state: restarted
        enabled: yes


